name: Deploy to GitHub Pages

# Triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - uses: actions/checkout@v3
    
    # Run basic tests
    - name: Run HTML validation
      run: |
        npm install -g html-validator-cli
        html-validator --file index.html
    
    # Check JavaScript syntax
    - name: Check JavaScript
      run: |
        node -c script.js
        echo "✅ JavaScript syntax is valid"
    
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./